musteriadi=input("Adınızı Giriniz: ")
musterisoyadi=input("Soyadınızı Giriniz: ")
mustericinsiyet=input("Cinsiyetinizi Giriniz: ")
musteritcno=input("TC Kimlik Numaranızı Giriniz: ")
musteridogumyili=input("Doğum Yılınızı Giriniz: ")
musteriadresbilgisi=input("Adres Bilgilerinizi Giriniz: ")
musteriyas=input("Yaşınızı Giriniz: ")
print("Müşteri Adı:", musteriadi)
print("Müşteri Soyadı:", musterisoyadi)
print("Müşteri Cinsiyeti:", mustericinsiyet)
print("Müşteri TC Kimlik Numarası:", musteritcno)
print("Müşteri Doğum Yılı:", musteridogumyili)   
print("Müşteri Adres Bilgisi:", musteriadresbilgisi)
print("Müşteri Yaşı:", musteriyas)